#!/usr/bin/env bash

if
  [[ -s "/home/aravindh/.rvm/gems/ruby-2.5.1@global/environment" ]]
then
  source "/home/aravindh/.rvm/gems/ruby-2.5.1@global/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/aravindh/.rvm/gems/ruby-2.5.1@global/environment'" >&2
  exit 1
fi
